### ISSUE TITLE
session_stickiness input not being respected

### ISSUE THREAD

**Issue by bryankaraffa** [rightscale-cookbooks/rs-haproxy#52]
Regardless if session_stickiness input is set to true or false, we are seeing the same behavior where this HAProxy config snippet is getting written:

```
defaults
     cookie SERVERID insert indirect nocache
```

Expectation is that when `session_stickiness == false`, this line does not get written to the config.
https://github.com/rightscale-cookbooks/rs-haproxy/blob/master/recipes/default.rb#L130-L132

Ultimately we are looking for a way to prevent `insert` and `indirect` cookie options, and hoping that setting session_stickiness to false via Input would accomplish this.

**Comment by rshade** [comment]
```
defaults
     timeout client 10s
     timeout server 10s
     timeout connect 10s

     log global
     mode http
     balance roundrobin
     option httplog
     option dontlognull
     option redispatch
     option httpchk GET /
     stats uri /haproxy-status
     stats auth statsuser:statspass
     http-check disable-on-404
     compression algo gzip
     compression type text/html text/plain text/css application/javascript application/json```

**Comment by rshade** [comment]
- name: default
  run_list:
  - recipe[fake::create_secrets]
  - recipe[rs-haproxy::default]
  - recipe[rs-haproxy::tags]
  - recipe[rs-haproxy::collectd]
  attributes:
    apt:
      compile_time_update: true
    rightscale:
      instance_uuid: '01-ABCDEFGH0123'
      monitoring_collector_http: 'localhost'
      RS_RLL_PORT: '12345'
    cloud:
      provider: 'vagrant'
      public_ips: ['192.0.2.2']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-haproxy:
      pools: ['test_example', 'appserver', 'example']
      incoming_port: 85
      stats_uri: '/haproxy-status'
      stats_user: 'statsuser'
      stats_password: 'statspass'
      health_check_uri: '/'
      session_stickiness: false

**Comment by tusharshahrs** [comment]
Resolved with updated code.
